/**
 * AUTO-GENERATED BY GENATEST — DO NOT EDIT
 *
 * Re-run the generator to update this file.
 * Custom methods belong in the user-facing class that extends this one.
 */

import type { Page, Locator } from 'playwright'

export class CreatePageBase {
  public readonly openNextJsDevToolsButton: Locator
  public readonly alert: Locator
  public readonly navigation: Locator
  public readonly main: Locator
  public readonly createNewListHeading: Locator
  public readonly morningRoutineTextbox: Locator
  public readonly task1NameTextbox: Locator
  public readonly removeTask1Button: Locator
  public readonly addTaskButton: Locator
  public readonly saveListButton: Locator
  public readonly navbarLogoGeneric: Locator
  public readonly navbarAvatarGeneric: Locator
  public readonly tasksListGeneric: Locator
  public readonly taskFormItemGeneric: Locator

  constructor(protected readonly page: Page) {
    this.openNextJsDevToolsButton = page.getByRole('button', { name: 'Open Next.js Dev Tools' })
    this.alert = page.locator('[id="__next-route-announcer__"]')
    this.navigation = page.getByTestId('navbar')
    this.main = page.getByTestId('create-list-page')
    this.createNewListHeading = page.getByRole('heading', { name: 'Create New List' })
    this.morningRoutineTextbox = page.getByTestId('list-name-input')
    this.task1NameTextbox = page.getByTestId('task-form-input')
    this.removeTask1Button = page.getByTestId('task-form-remove')
    this.addTaskButton = page.getByTestId('add-task-button')
    this.saveListButton = page.getByTestId('save-list-button')
    this.navbarLogoGeneric = page.locator('[data-testid="navbar-logo"]')
    this.navbarAvatarGeneric = page.locator('[data-testid="navbar-avatar"]')
    this.tasksListGeneric = page.locator('[data-testid="tasks-list"]')
    this.taskFormItemGeneric = page.locator('[data-testid="task-form-item"]')
  }
}
