/**
 * AUTO-GENERATED BY GENATEST — DO NOT EDIT
 *
 * Re-run the generator to update this file.
 * Custom methods belong in the user-facing class that extends this one.
 */

import type { Page, Locator } from 'playwright'

export class HomePageBase {
  public readonly openNextJsDevToolsButton: Locator
  public readonly alert: Locator
  public readonly navigation: Locator
  public readonly main: Locator
  public readonly myListsHeading: Locator
  public readonly newListButton: Locator
  public readonly img: Locator
  public readonly toggleProgressOverviewButton: Locator
  public readonly img2: Locator
  public readonly img3: Locator
  public readonly img4: Locator
  public readonly img5: Locator
  public readonly img6: Locator
  public readonly img7: Locator
  public readonly img8: Locator
  public readonly img9: Locator
  public readonly img10: Locator
  public readonly img11: Locator
  public readonly img12: Locator
  public readonly img13: Locator
  public readonly img14: Locator
  public readonly img15: Locator
  public readonly navbarLogoGeneric: Locator
  public readonly navbarAvatarGeneric: Locator
  public readonly progressOverviewGeneric: Locator
  public readonly progressOverviewChartGeneric: Locator
  public readonly listsContainerGeneric: Locator

  constructor(protected readonly page: Page) {
    this.openNextJsDevToolsButton = page.getByRole('button', { name: 'Open Next.js Dev Tools' })
    this.alert = page.locator('[id="__next-route-announcer__"]')
    this.navigation = page.getByTestId('navbar')
    this.main = page.getByTestId('my-lists-page')
    this.myListsHeading = page.getByRole('heading', { name: 'My Lists' })
    this.newListButton = page.getByTestId('new-list-button')
    this.img = page.locator('svg').first()
    this.toggleProgressOverviewButton = page.getByTestId('progress-overview-toggle')
    this.img2 = page.getByLabel('TC-L-01 DailyDo List').locator('svg')
    this.img3 = page.getByLabel('sdf').locator('svg')
    this.img4 = page.getByLabel('Assertum TC-L-').locator('svg')
    this.img5 = page.locator('svg').nth(5)
    this.img6 = page.locator('div:nth-child(5) > .flex.justify-between > .flex > .lucide')
    this.img7 = page.locator('div:nth-child(6) > .flex.justify-between > .flex > .lucide')
    this.img8 = page.locator('div:nth-child(7) > .flex.justify-between > .flex > .lucide')
    this.img9 = page.locator('div:nth-child(8) > .flex.justify-between > .flex > .lucide')
    this.img10 = page.locator('div:nth-child(9) > .flex.justify-between > .flex > .lucide')
    this.img11 = page.locator('div:nth-child(10) > .flex.justify-between > .flex > .lucide')
    this.img12 = page.locator('div:nth-child(11) > .flex.justify-between > .flex > .lucide')
    this.img13 = page.locator('div:nth-child(12) > .flex.justify-between > .flex > .lucide')
    this.img14 = page.locator('div:nth-child(13) > .flex.justify-between > .flex > .lucide')
    this.img15 = page.locator('div:nth-child(14) > .flex.justify-between > .flex > .lucide')
    this.navbarLogoGeneric = page.locator('[data-testid="navbar-logo"]')
    this.navbarAvatarGeneric = page.locator('[data-testid="navbar-avatar"]')
    this.progressOverviewGeneric = page.locator('[data-testid="progress-overview"]')
    this.progressOverviewChartGeneric = page.locator('[data-testid="progress-overview-chart"]')
    this.listsContainerGeneric = page.locator('[data-testid="lists-container"]')
  }
}
