/**
 * AUTO-GENERATED BY GENATEST — DO NOT EDIT
 *
 * Re-run the generator to update this file.
 * Custom methods belong in the user-facing class that extends this one.
 */

import type { Page, Locator } from 'playwright'

export class ListPageBase {
  public readonly openNextJsDevToolsButton: Locator
  public readonly alert: Locator
  public readonly navigation: Locator
  public readonly main: Locator
  public readonly backButton: Locator
  public readonly img: Locator
  public readonly tcL01DailydoListHeading: Locator
  public readonly editFirstTaskUserStoryButton: Locator
  public readonly navbarLogoGeneric: Locator
  public readonly navbarAvatarGeneric: Locator
  public readonly progressCounterGeneric: Locator
  public readonly pendingSectionGeneric: Locator
  public readonly taskItemGeneric: Locator
  public readonly taskCheckboxGeneric: Locator
  public readonly taskNameGeneric: Locator

  constructor(protected readonly page: Page) {
    this.openNextJsDevToolsButton = page.getByRole('button', { name: 'Open Next.js Dev Tools' })
    this.alert = page.locator('[id="__next-route-announcer__"]')
    this.navigation = page.getByTestId('navbar')
    this.main = page.getByTestId('progress-view-page')
    this.backButton = page.getByTestId('back-button')
    this.img = page.locator('svg').nth(1)
    this.tcL01DailydoListHeading = page.getByRole('heading', { name: 'TC-L-01 DailyDo List' })
    this.editFirstTaskUserStoryButton = page.getByTestId('task-edit')
    this.navbarLogoGeneric = page.locator('[data-testid="navbar-logo"]')
    this.navbarAvatarGeneric = page.locator('[data-testid="navbar-avatar"]')
    this.progressCounterGeneric = page.locator('[data-testid="progress-counter"]')
    this.pendingSectionGeneric = page.locator('[data-testid="pending-section"]')
    this.taskItemGeneric = page.locator('[data-testid="task-item"]')
    this.taskCheckboxGeneric = page.locator('[data-testid="task-checkbox"]')
    this.taskNameGeneric = page.locator('[data-testid="task-name"]')
  }
}
